/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as pagesRouteRouteImport } from './routes/(pages)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SettingsWikiAssistantRouteImport } from './routes/settings/wiki-assistant'
import { Route as SettingsTicketsRouteImport } from './routes/settings/tickets'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsPaymentsRouteImport } from './routes/settings/payments'
import { Route as SettingsCreditsRouteImport } from './routes/settings/credits'
import { Route as SettingsChatRouteImport } from './routes/settings/chat'
import { Route as SettingsBillingRouteImport } from './routes/settings/billing'
import { Route as SettingsApikeysRouteImport } from './routes/settings/apikeys'
import { Route as SettingsAiSupportRouteImport } from './routes/settings/ai-support'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ApiTicketsRouteImport } from './routes/api/tickets'
import { Route as ApiCreditsRouteImport } from './routes/api/credits'
import { Route as ApiApikeysRouteImport } from './routes/api/apikeys'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminTicketsRouteImport } from './routes/admin/tickets'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin/subscriptions'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminPostsRouteImport } from './routes/admin/posts'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminInviteCodesRouteImport } from './routes/admin/invite-codes'
import { Route as AdminCreditsRouteImport } from './routes/admin/credits'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as pagesTermsOfServiceRouteImport } from './routes/(pages)/terms-of-service'
import { Route as pagesPrivacyPolicyRouteImport } from './routes/(pages)/privacy-policy'
import { Route as authVerifyEmailRouteImport } from './routes/(auth)/verify-email'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ApiWikiContextsRouteImport } from './routes/api/wiki/contexts'
import { Route as ApiWikiContextRouteImport } from './routes/api/wiki/context'
import { Route as ApiWikiAssetRouteImport } from './routes/api/wiki/asset'
import { Route as ApiWikiAskRouteImport } from './routes/api/wiki/ask'
import { Route as ApiUserProfileRouteImport } from './routes/api/user/profile'
import { Route as ApiUserPermissionsRouteImport } from './routes/api/user/permissions'
import { Route as ApiUserOrdersRouteImport } from './routes/api/user/orders'
import { Route as ApiUserIsEmailVerifiedRouteImport } from './routes/api/user/is-email-verified'
import { Route as ApiUserInfoRouteImport } from './routes/api/user/info'
import { Route as ApiUserCreditsRouteImport } from './routes/api/user/credits'
import { Route as ApiTicketsIdRouteImport } from './routes/api/tickets/$id'
import { Route as ApiStorageUploadImageRouteImport } from './routes/api/storage/upload-image'
import { Route as ApiPaymentCheckoutRouteImport } from './routes/api/payment/checkout'
import { Route as ApiPaymentCallbackRouteImport } from './routes/api/payment/callback'
import { Route as ApiInviteCodesValidateRouteImport } from './routes/api/invite-codes/validate'
import { Route as ApiInviteCodesRedeemRouteImport } from './routes/api/invite-codes/redeem'
import { Route as ApiInternalSessionRouteImport } from './routes/api/internal/session'
import { Route as ApiInternalCreditsRouteImport } from './routes/api/internal/credits'
import { Route as ApiDocqaIngestRouteImport } from './routes/api/docqa/ingest'
import { Route as ApiConfigPublicRouteImport } from './routes/api/config/public'
import { Route as ApiAuthTokenRouteImport } from './routes/api/auth/token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAiSupportWidgetAppearanceRouteImport } from './routes/api/ai-support/widget-appearance'
import { Route as ApiAiSupportUsageRouteImport } from './routes/api/ai-support/usage'
import { Route as ApiAiSupportSyncJobsRouteImport } from './routes/api/ai-support/sync-jobs'
import { Route as ApiAiSupportPromptPersonaRouteImport } from './routes/api/ai-support/prompt-persona'
import { Route as ApiAiSupportOverviewRouteImport } from './routes/api/ai-support/overview'
import { Route as ApiAiSupportLeadsRouteImport } from './routes/api/ai-support/leads'
import { Route as ApiAiSupportLaunchOperationsRouteImport } from './routes/api/ai-support/launch-operations'
import { Route as ApiAiSupportKnowledgeSourcesRouteImport } from './routes/api/ai-support/knowledge-sources'
import { Route as ApiAiSupportInstallCheckRouteImport } from './routes/api/ai-support/install-check'
import { Route as ApiAiSupportHumanSupportSettingsRouteImport } from './routes/api/ai-support/human-support-settings'
import { Route as ApiAiSupportEscalationsRouteImport } from './routes/api/ai-support/escalations'
import { Route as ApiAiSupportConversationsRouteImport } from './routes/api/ai-support/conversations'
import { Route as ApiAiSupportConversationMessagesRouteImport } from './routes/api/ai-support/conversation-messages'
import { Route as ApiAiSupportConfigVersionsRouteImport } from './routes/api/ai-support/config-versions'
import { Route as ApiAiSupportChatbotsRouteImport } from './routes/api/ai-support/chatbots'
import { Route as ApiAiSupportAuditLogsRouteImport } from './routes/api/ai-support/audit-logs'
import { Route as ApiAiSupportAgentTokensRouteImport } from './routes/api/ai-support/agent-tokens'
import { Route as ApiAiSupportAgentRunsRouteImport } from './routes/api/ai-support/agent-runs'
import { Route as ApiAdminTicketsRouteImport } from './routes/api/admin/tickets'
import { Route as ApiAdminSubscriptionsRouteImport } from './routes/api/admin/subscriptions'
import { Route as ApiAdminPostsRouteImport } from './routes/api/admin/posts'
import { Route as ApiAdminPermissionsRouteImport } from './routes/api/admin/permissions'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminInviteCodesRouteImport } from './routes/api/admin/invite-codes'
import { Route as ApiAdminCreditsRouteImport } from './routes/api/admin/credits'
import { Route as ApiAdminConfigRouteImport } from './routes/api/admin/config'
import { Route as ApiAdminCategoriesRouteImport } from './routes/api/admin/categories'
import { Route as ApiUserSubscriptionsIndexRouteImport } from './routes/api/user/subscriptions/index'
import { Route as ApiAdminUsersIndexRouteImport } from './routes/api/admin/users/index'
import { Route as ApiAdminRolesIndexRouteImport } from './routes/api/admin/roles/index'
import { Route as ApiUserSubscriptionsCurrentRouteImport } from './routes/api/user/subscriptions/current'
import { Route as ApiUserSubscriptionsCancelRouteImport } from './routes/api/user/subscriptions/cancel'
import { Route as ApiPaymentNotifyProviderRouteImport } from './routes/api/payment/notify/$provider'
import { Route as ApiAiSupportWidgetPublicKeyRouteImport } from './routes/api/ai-support/widget/$publicKey'
import { Route as ApiAdminUsersCreditsRouteImport } from './routes/api/admin/users/credits'
import { Route as ApiAdminTicketsIdRouteImport } from './routes/api/admin/tickets/$id'
import { Route as ApiAdminSettingsTestRouteImport } from './routes/api/admin/settings/test'
import { Route as ApiAdminRolesPermissionsRouteImport } from './routes/api/admin/roles/permissions'
import { Route as ApiAdminRolesAssignRouteImport } from './routes/api/admin/roles/assign'
import { Route as ApiAdminConfigCustomRouteImport } from './routes/api/admin/config/custom'
import { Route as ApiAiSupportWidgetPublicKeyMessagesRouteImport } from './routes/api/ai-support/widget/$publicKey/messages'
import { Route as ApiAiSupportWidgetPublicKeyLeadsRouteImport } from './routes/api/ai-support/widget/$publicKey/leads'
import { Route as ApiAiSupportWidgetPublicKeyEscalationsRouteImport } from './routes/api/ai-support/widget/$publicKey/escalations'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const pagesRouteRoute = pagesRouteRouteImport.update({
  id: '/(pages)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SettingsWikiAssistantRoute = SettingsWikiAssistantRouteImport.update({
  id: '/wiki-assistant',
  path: '/wiki-assistant',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsTicketsRoute = SettingsTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsPaymentsRoute = SettingsPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsCreditsRoute = SettingsCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsChatRoute = SettingsChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsBillingRoute = SettingsBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsApikeysRoute = SettingsApikeysRouteImport.update({
  id: '/apikeys',
  path: '/apikeys',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAiSupportRoute = SettingsAiSupportRouteImport.update({
  id: '/ai-support',
  path: '/ai-support',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsRoute = ApiTicketsRouteImport.update({
  id: '/api/tickets',
  path: '/api/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreditsRoute = ApiCreditsRouteImport.update({
  id: '/api/credits',
  path: '/api/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiApikeysRoute = ApiApikeysRouteImport.update({
  id: '/api/apikeys',
  path: '/api/apikeys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTicketsRoute = AdminTicketsRouteImport.update({
  id: '/tickets',
  path: '/tickets',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPostsRoute = AdminPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInviteCodesRoute = AdminInviteCodesRouteImport.update({
  id: '/invite-codes',
  path: '/invite-codes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCreditsRoute = AdminCreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const pagesTermsOfServiceRoute = pagesTermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => pagesRouteRoute,
} as any)
const pagesPrivacyPolicyRoute = pagesPrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => pagesRouteRoute,
} as any)
const authVerifyEmailRoute = authVerifyEmailRouteImport.update({
  id: '/(auth)/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWikiContextsRoute = ApiWikiContextsRouteImport.update({
  id: '/api/wiki/contexts',
  path: '/api/wiki/contexts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWikiContextRoute = ApiWikiContextRouteImport.update({
  id: '/api/wiki/context',
  path: '/api/wiki/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWikiAssetRoute = ApiWikiAssetRouteImport.update({
  id: '/api/wiki/asset',
  path: '/api/wiki/asset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWikiAskRoute = ApiWikiAskRouteImport.update({
  id: '/api/wiki/ask',
  path: '/api/wiki/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserProfileRoute = ApiUserProfileRouteImport.update({
  id: '/api/user/profile',
  path: '/api/user/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserPermissionsRoute = ApiUserPermissionsRouteImport.update({
  id: '/api/user/permissions',
  path: '/api/user/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserOrdersRoute = ApiUserOrdersRouteImport.update({
  id: '/api/user/orders',
  path: '/api/user/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserIsEmailVerifiedRoute = ApiUserIsEmailVerifiedRouteImport.update({
  id: '/api/user/is-email-verified',
  path: '/api/user/is-email-verified',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserInfoRoute = ApiUserInfoRouteImport.update({
  id: '/api/user/info',
  path: '/api/user/info',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserCreditsRoute = ApiUserCreditsRouteImport.update({
  id: '/api/user/credits',
  path: '/api/user/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsIdRoute = ApiTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiTicketsRoute,
} as any)
const ApiStorageUploadImageRoute = ApiStorageUploadImageRouteImport.update({
  id: '/api/storage/upload-image',
  path: '/api/storage/upload-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCheckoutRoute = ApiPaymentCheckoutRouteImport.update({
  id: '/api/payment/checkout',
  path: '/api/payment/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCallbackRoute = ApiPaymentCallbackRouteImport.update({
  id: '/api/payment/callback',
  path: '/api/payment/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInviteCodesValidateRoute = ApiInviteCodesValidateRouteImport.update({
  id: '/api/invite-codes/validate',
  path: '/api/invite-codes/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInviteCodesRedeemRoute = ApiInviteCodesRedeemRouteImport.update({
  id: '/api/invite-codes/redeem',
  path: '/api/invite-codes/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalSessionRoute = ApiInternalSessionRouteImport.update({
  id: '/api/internal/session',
  path: '/api/internal/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalCreditsRoute = ApiInternalCreditsRouteImport.update({
  id: '/api/internal/credits',
  path: '/api/internal/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocqaIngestRoute = ApiDocqaIngestRouteImport.update({
  id: '/api/docqa/ingest',
  path: '/api/docqa/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigPublicRoute = ApiConfigPublicRouteImport.update({
  id: '/api/config/public',
  path: '/api/config/public',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTokenRoute = ApiAuthTokenRouteImport.update({
  id: '/api/auth/token',
  path: '/api/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportWidgetAppearanceRoute =
  ApiAiSupportWidgetAppearanceRouteImport.update({
    id: '/api/ai-support/widget-appearance',
    path: '/api/ai-support/widget-appearance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportUsageRoute = ApiAiSupportUsageRouteImport.update({
  id: '/api/ai-support/usage',
  path: '/api/ai-support/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportSyncJobsRoute = ApiAiSupportSyncJobsRouteImport.update({
  id: '/api/ai-support/sync-jobs',
  path: '/api/ai-support/sync-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportPromptPersonaRoute =
  ApiAiSupportPromptPersonaRouteImport.update({
    id: '/api/ai-support/prompt-persona',
    path: '/api/ai-support/prompt-persona',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportOverviewRoute = ApiAiSupportOverviewRouteImport.update({
  id: '/api/ai-support/overview',
  path: '/api/ai-support/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportLeadsRoute = ApiAiSupportLeadsRouteImport.update({
  id: '/api/ai-support/leads',
  path: '/api/ai-support/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportLaunchOperationsRoute =
  ApiAiSupportLaunchOperationsRouteImport.update({
    id: '/api/ai-support/launch-operations',
    path: '/api/ai-support/launch-operations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportKnowledgeSourcesRoute =
  ApiAiSupportKnowledgeSourcesRouteImport.update({
    id: '/api/ai-support/knowledge-sources',
    path: '/api/ai-support/knowledge-sources',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportInstallCheckRoute =
  ApiAiSupportInstallCheckRouteImport.update({
    id: '/api/ai-support/install-check',
    path: '/api/ai-support/install-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportHumanSupportSettingsRoute =
  ApiAiSupportHumanSupportSettingsRouteImport.update({
    id: '/api/ai-support/human-support-settings',
    path: '/api/ai-support/human-support-settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportEscalationsRoute = ApiAiSupportEscalationsRouteImport.update({
  id: '/api/ai-support/escalations',
  path: '/api/ai-support/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportConversationsRoute =
  ApiAiSupportConversationsRouteImport.update({
    id: '/api/ai-support/conversations',
    path: '/api/ai-support/conversations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportConversationMessagesRoute =
  ApiAiSupportConversationMessagesRouteImport.update({
    id: '/api/ai-support/conversation-messages',
    path: '/api/ai-support/conversation-messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportConfigVersionsRoute =
  ApiAiSupportConfigVersionsRouteImport.update({
    id: '/api/ai-support/config-versions',
    path: '/api/ai-support/config-versions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportChatbotsRoute = ApiAiSupportChatbotsRouteImport.update({
  id: '/api/ai-support/chatbots',
  path: '/api/ai-support/chatbots',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportAuditLogsRoute = ApiAiSupportAuditLogsRouteImport.update({
  id: '/api/ai-support/audit-logs',
  path: '/api/ai-support/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportAgentTokensRoute = ApiAiSupportAgentTokensRouteImport.update({
  id: '/api/ai-support/agent-tokens',
  path: '/api/ai-support/agent-tokens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSupportAgentRunsRoute = ApiAiSupportAgentRunsRouteImport.update({
  id: '/api/ai-support/agent-runs',
  path: '/api/ai-support/agent-runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTicketsRoute = ApiAdminTicketsRouteImport.update({
  id: '/api/admin/tickets',
  path: '/api/admin/tickets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSubscriptionsRoute = ApiAdminSubscriptionsRouteImport.update({
  id: '/api/admin/subscriptions',
  path: '/api/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPostsRoute = ApiAdminPostsRouteImport.update({
  id: '/api/admin/posts',
  path: '/api/admin/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPermissionsRoute = ApiAdminPermissionsRouteImport.update({
  id: '/api/admin/permissions',
  path: '/api/admin/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInviteCodesRoute = ApiAdminInviteCodesRouteImport.update({
  id: '/api/admin/invite-codes',
  path: '/api/admin/invite-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCreditsRoute = ApiAdminCreditsRouteImport.update({
  id: '/api/admin/credits',
  path: '/api/admin/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigRoute = ApiAdminConfigRouteImport.update({
  id: '/api/admin/config',
  path: '/api/admin/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCategoriesRoute = ApiAdminCategoriesRouteImport.update({
  id: '/api/admin/categories',
  path: '/api/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSubscriptionsIndexRoute =
  ApiUserSubscriptionsIndexRouteImport.update({
    id: '/api/user/subscriptions/',
    path: '/api/user/subscriptions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersIndexRoute = ApiAdminUsersIndexRouteImport.update({
  id: '/api/admin/users/',
  path: '/api/admin/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRolesIndexRoute = ApiAdminRolesIndexRouteImport.update({
  id: '/api/admin/roles/',
  path: '/api/admin/roles/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUserSubscriptionsCurrentRoute =
  ApiUserSubscriptionsCurrentRouteImport.update({
    id: '/api/user/subscriptions/current',
    path: '/api/user/subscriptions/current',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiUserSubscriptionsCancelRoute =
  ApiUserSubscriptionsCancelRouteImport.update({
    id: '/api/user/subscriptions/cancel',
    path: '/api/user/subscriptions/cancel',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentNotifyProviderRoute =
  ApiPaymentNotifyProviderRouteImport.update({
    id: '/api/payment/notify/$provider',
    path: '/api/payment/notify/$provider',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAiSupportWidgetPublicKeyRoute =
  ApiAiSupportWidgetPublicKeyRouteImport.update({
    id: '/api/ai-support/widget/$publicKey',
    path: '/api/ai-support/widget/$publicKey',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminUsersCreditsRoute = ApiAdminUsersCreditsRouteImport.update({
  id: '/api/admin/users/credits',
  path: '/api/admin/users/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTicketsIdRoute = ApiAdminTicketsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiAdminTicketsRoute,
} as any)
const ApiAdminSettingsTestRoute = ApiAdminSettingsTestRouteImport.update({
  id: '/api/admin/settings/test',
  path: '/api/admin/settings/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRolesPermissionsRoute =
  ApiAdminRolesPermissionsRouteImport.update({
    id: '/api/admin/roles/permissions',
    path: '/api/admin/roles/permissions',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminRolesAssignRoute = ApiAdminRolesAssignRouteImport.update({
  id: '/api/admin/roles/assign',
  path: '/api/admin/roles/assign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminConfigCustomRoute = ApiAdminConfigCustomRouteImport.update({
  id: '/custom',
  path: '/custom',
  getParentRoute: () => ApiAdminConfigRoute,
} as any)
const ApiAiSupportWidgetPublicKeyMessagesRoute =
  ApiAiSupportWidgetPublicKeyMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => ApiAiSupportWidgetPublicKeyRoute,
  } as any)
const ApiAiSupportWidgetPublicKeyLeadsRoute =
  ApiAiSupportWidgetPublicKeyLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => ApiAiSupportWidgetPublicKeyRoute,
  } as any)
const ApiAiSupportWidgetPublicKeyEscalationsRoute =
  ApiAiSupportWidgetPublicKeyEscalationsRouteImport.update({
    id: '/escalations',
    path: '/escalations',
    getParentRoute: () => ApiAiSupportWidgetPublicKeyRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/privacy-policy': typeof pagesPrivacyPolicyRoute
  '/terms-of-service': typeof pagesTermsOfServiceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/invite-codes': typeof AdminInviteCodesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/apikeys': typeof ApiApikeysRoute
  '/api/credits': typeof ApiCreditsRoute
  '/api/tickets': typeof ApiTicketsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/ai-support': typeof SettingsAiSupportRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tickets': typeof SettingsTicketsRoute
  '/settings/wiki-assistant': typeof SettingsWikiAssistantRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/config': typeof ApiAdminConfigRouteWithChildren
  '/api/admin/credits': typeof ApiAdminCreditsRoute
  '/api/admin/invite-codes': typeof ApiAdminInviteCodesRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/permissions': typeof ApiAdminPermissionsRoute
  '/api/admin/posts': typeof ApiAdminPostsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/tickets': typeof ApiAdminTicketsRouteWithChildren
  '/api/ai-support/agent-runs': typeof ApiAiSupportAgentRunsRoute
  '/api/ai-support/agent-tokens': typeof ApiAiSupportAgentTokensRoute
  '/api/ai-support/audit-logs': typeof ApiAiSupportAuditLogsRoute
  '/api/ai-support/chatbots': typeof ApiAiSupportChatbotsRoute
  '/api/ai-support/config-versions': typeof ApiAiSupportConfigVersionsRoute
  '/api/ai-support/conversation-messages': typeof ApiAiSupportConversationMessagesRoute
  '/api/ai-support/conversations': typeof ApiAiSupportConversationsRoute
  '/api/ai-support/escalations': typeof ApiAiSupportEscalationsRoute
  '/api/ai-support/human-support-settings': typeof ApiAiSupportHumanSupportSettingsRoute
  '/api/ai-support/install-check': typeof ApiAiSupportInstallCheckRoute
  '/api/ai-support/knowledge-sources': typeof ApiAiSupportKnowledgeSourcesRoute
  '/api/ai-support/launch-operations': typeof ApiAiSupportLaunchOperationsRoute
  '/api/ai-support/leads': typeof ApiAiSupportLeadsRoute
  '/api/ai-support/overview': typeof ApiAiSupportOverviewRoute
  '/api/ai-support/prompt-persona': typeof ApiAiSupportPromptPersonaRoute
  '/api/ai-support/sync-jobs': typeof ApiAiSupportSyncJobsRoute
  '/api/ai-support/usage': typeof ApiAiSupportUsageRoute
  '/api/ai-support/widget-appearance': typeof ApiAiSupportWidgetAppearanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/config/public': typeof ApiConfigPublicRoute
  '/api/docqa/ingest': typeof ApiDocqaIngestRoute
  '/api/internal/credits': typeof ApiInternalCreditsRoute
  '/api/internal/session': typeof ApiInternalSessionRoute
  '/api/invite-codes/redeem': typeof ApiInviteCodesRedeemRoute
  '/api/invite-codes/validate': typeof ApiInviteCodesValidateRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/storage/upload-image': typeof ApiStorageUploadImageRoute
  '/api/tickets/$id': typeof ApiTicketsIdRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/user/info': typeof ApiUserInfoRoute
  '/api/user/is-email-verified': typeof ApiUserIsEmailVerifiedRoute
  '/api/user/orders': typeof ApiUserOrdersRoute
  '/api/user/permissions': typeof ApiUserPermissionsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/wiki/ask': typeof ApiWikiAskRoute
  '/api/wiki/asset': typeof ApiWikiAssetRoute
  '/api/wiki/context': typeof ApiWikiContextRoute
  '/api/wiki/contexts': typeof ApiWikiContextsRoute
  '/api/admin/config/custom': typeof ApiAdminConfigCustomRoute
  '/api/admin/roles/assign': typeof ApiAdminRolesAssignRoute
  '/api/admin/roles/permissions': typeof ApiAdminRolesPermissionsRoute
  '/api/admin/settings/test': typeof ApiAdminSettingsTestRoute
  '/api/admin/tickets/$id': typeof ApiAdminTicketsIdRoute
  '/api/admin/users/credits': typeof ApiAdminUsersCreditsRoute
  '/api/ai-support/widget/$publicKey': typeof ApiAiSupportWidgetPublicKeyRouteWithChildren
  '/api/payment/notify/$provider': typeof ApiPaymentNotifyProviderRoute
  '/api/user/subscriptions/cancel': typeof ApiUserSubscriptionsCancelRoute
  '/api/user/subscriptions/current': typeof ApiUserSubscriptionsCurrentRoute
  '/api/admin/roles/': typeof ApiAdminRolesIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/user/subscriptions/': typeof ApiUserSubscriptionsIndexRoute
  '/api/ai-support/widget/$publicKey/escalations': typeof ApiAiSupportWidgetPublicKeyEscalationsRoute
  '/api/ai-support/widget/$publicKey/leads': typeof ApiAiSupportWidgetPublicKeyLeadsRoute
  '/api/ai-support/widget/$publicKey/messages': typeof ApiAiSupportWidgetPublicKeyMessagesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/verify-email': typeof authVerifyEmailRoute
  '/privacy-policy': typeof pagesPrivacyPolicyRoute
  '/terms-of-service': typeof pagesTermsOfServiceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/invite-codes': typeof AdminInviteCodesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/apikeys': typeof ApiApikeysRoute
  '/api/credits': typeof ApiCreditsRoute
  '/api/tickets': typeof ApiTicketsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/ai-support': typeof SettingsAiSupportRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tickets': typeof SettingsTicketsRoute
  '/settings/wiki-assistant': typeof SettingsWikiAssistantRoute
  '/admin': typeof AdminIndexRoute
  '/blog': typeof BlogIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/config': typeof ApiAdminConfigRouteWithChildren
  '/api/admin/credits': typeof ApiAdminCreditsRoute
  '/api/admin/invite-codes': typeof ApiAdminInviteCodesRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/permissions': typeof ApiAdminPermissionsRoute
  '/api/admin/posts': typeof ApiAdminPostsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/tickets': typeof ApiAdminTicketsRouteWithChildren
  '/api/ai-support/agent-runs': typeof ApiAiSupportAgentRunsRoute
  '/api/ai-support/agent-tokens': typeof ApiAiSupportAgentTokensRoute
  '/api/ai-support/audit-logs': typeof ApiAiSupportAuditLogsRoute
  '/api/ai-support/chatbots': typeof ApiAiSupportChatbotsRoute
  '/api/ai-support/config-versions': typeof ApiAiSupportConfigVersionsRoute
  '/api/ai-support/conversation-messages': typeof ApiAiSupportConversationMessagesRoute
  '/api/ai-support/conversations': typeof ApiAiSupportConversationsRoute
  '/api/ai-support/escalations': typeof ApiAiSupportEscalationsRoute
  '/api/ai-support/human-support-settings': typeof ApiAiSupportHumanSupportSettingsRoute
  '/api/ai-support/install-check': typeof ApiAiSupportInstallCheckRoute
  '/api/ai-support/knowledge-sources': typeof ApiAiSupportKnowledgeSourcesRoute
  '/api/ai-support/launch-operations': typeof ApiAiSupportLaunchOperationsRoute
  '/api/ai-support/leads': typeof ApiAiSupportLeadsRoute
  '/api/ai-support/overview': typeof ApiAiSupportOverviewRoute
  '/api/ai-support/prompt-persona': typeof ApiAiSupportPromptPersonaRoute
  '/api/ai-support/sync-jobs': typeof ApiAiSupportSyncJobsRoute
  '/api/ai-support/usage': typeof ApiAiSupportUsageRoute
  '/api/ai-support/widget-appearance': typeof ApiAiSupportWidgetAppearanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/config/public': typeof ApiConfigPublicRoute
  '/api/docqa/ingest': typeof ApiDocqaIngestRoute
  '/api/internal/credits': typeof ApiInternalCreditsRoute
  '/api/internal/session': typeof ApiInternalSessionRoute
  '/api/invite-codes/redeem': typeof ApiInviteCodesRedeemRoute
  '/api/invite-codes/validate': typeof ApiInviteCodesValidateRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/storage/upload-image': typeof ApiStorageUploadImageRoute
  '/api/tickets/$id': typeof ApiTicketsIdRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/user/info': typeof ApiUserInfoRoute
  '/api/user/is-email-verified': typeof ApiUserIsEmailVerifiedRoute
  '/api/user/orders': typeof ApiUserOrdersRoute
  '/api/user/permissions': typeof ApiUserPermissionsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/wiki/ask': typeof ApiWikiAskRoute
  '/api/wiki/asset': typeof ApiWikiAssetRoute
  '/api/wiki/context': typeof ApiWikiContextRoute
  '/api/wiki/contexts': typeof ApiWikiContextsRoute
  '/api/admin/config/custom': typeof ApiAdminConfigCustomRoute
  '/api/admin/roles/assign': typeof ApiAdminRolesAssignRoute
  '/api/admin/roles/permissions': typeof ApiAdminRolesPermissionsRoute
  '/api/admin/settings/test': typeof ApiAdminSettingsTestRoute
  '/api/admin/tickets/$id': typeof ApiAdminTicketsIdRoute
  '/api/admin/users/credits': typeof ApiAdminUsersCreditsRoute
  '/api/ai-support/widget/$publicKey': typeof ApiAiSupportWidgetPublicKeyRouteWithChildren
  '/api/payment/notify/$provider': typeof ApiPaymentNotifyProviderRoute
  '/api/user/subscriptions/cancel': typeof ApiUserSubscriptionsCancelRoute
  '/api/user/subscriptions/current': typeof ApiUserSubscriptionsCurrentRoute
  '/api/admin/roles': typeof ApiAdminRolesIndexRoute
  '/api/admin/users': typeof ApiAdminUsersIndexRoute
  '/api/user/subscriptions': typeof ApiUserSubscriptionsIndexRoute
  '/api/ai-support/widget/$publicKey/escalations': typeof ApiAiSupportWidgetPublicKeyEscalationsRoute
  '/api/ai-support/widget/$publicKey/leads': typeof ApiAiSupportWidgetPublicKeyLeadsRoute
  '/api/ai-support/widget/$publicKey/messages': typeof ApiAiSupportWidgetPublicKeyMessagesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(pages)': typeof pagesRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(auth)/verify-email': typeof authVerifyEmailRoute
  '/(pages)/privacy-policy': typeof pagesPrivacyPolicyRoute
  '/(pages)/terms-of-service': typeof pagesTermsOfServiceRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/credits': typeof AdminCreditsRoute
  '/admin/invite-codes': typeof AdminInviteCodesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/posts': typeof AdminPostsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/admin/tickets': typeof AdminTicketsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/apikeys': typeof ApiApikeysRoute
  '/api/credits': typeof ApiCreditsRoute
  '/api/tickets': typeof ApiTicketsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/settings/ai-support': typeof SettingsAiSupportRoute
  '/settings/apikeys': typeof SettingsApikeysRoute
  '/settings/billing': typeof SettingsBillingRoute
  '/settings/chat': typeof SettingsChatRoute
  '/settings/credits': typeof SettingsCreditsRoute
  '/settings/payments': typeof SettingsPaymentsRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/tickets': typeof SettingsTicketsRoute
  '/settings/wiki-assistant': typeof SettingsWikiAssistantRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/api/admin/categories': typeof ApiAdminCategoriesRoute
  '/api/admin/config': typeof ApiAdminConfigRouteWithChildren
  '/api/admin/credits': typeof ApiAdminCreditsRoute
  '/api/admin/invite-codes': typeof ApiAdminInviteCodesRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/permissions': typeof ApiAdminPermissionsRoute
  '/api/admin/posts': typeof ApiAdminPostsRoute
  '/api/admin/subscriptions': typeof ApiAdminSubscriptionsRoute
  '/api/admin/tickets': typeof ApiAdminTicketsRouteWithChildren
  '/api/ai-support/agent-runs': typeof ApiAiSupportAgentRunsRoute
  '/api/ai-support/agent-tokens': typeof ApiAiSupportAgentTokensRoute
  '/api/ai-support/audit-logs': typeof ApiAiSupportAuditLogsRoute
  '/api/ai-support/chatbots': typeof ApiAiSupportChatbotsRoute
  '/api/ai-support/config-versions': typeof ApiAiSupportConfigVersionsRoute
  '/api/ai-support/conversation-messages': typeof ApiAiSupportConversationMessagesRoute
  '/api/ai-support/conversations': typeof ApiAiSupportConversationsRoute
  '/api/ai-support/escalations': typeof ApiAiSupportEscalationsRoute
  '/api/ai-support/human-support-settings': typeof ApiAiSupportHumanSupportSettingsRoute
  '/api/ai-support/install-check': typeof ApiAiSupportInstallCheckRoute
  '/api/ai-support/knowledge-sources': typeof ApiAiSupportKnowledgeSourcesRoute
  '/api/ai-support/launch-operations': typeof ApiAiSupportLaunchOperationsRoute
  '/api/ai-support/leads': typeof ApiAiSupportLeadsRoute
  '/api/ai-support/overview': typeof ApiAiSupportOverviewRoute
  '/api/ai-support/prompt-persona': typeof ApiAiSupportPromptPersonaRoute
  '/api/ai-support/sync-jobs': typeof ApiAiSupportSyncJobsRoute
  '/api/ai-support/usage': typeof ApiAiSupportUsageRoute
  '/api/ai-support/widget-appearance': typeof ApiAiSupportWidgetAppearanceRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
  '/api/config/public': typeof ApiConfigPublicRoute
  '/api/docqa/ingest': typeof ApiDocqaIngestRoute
  '/api/internal/credits': typeof ApiInternalCreditsRoute
  '/api/internal/session': typeof ApiInternalSessionRoute
  '/api/invite-codes/redeem': typeof ApiInviteCodesRedeemRoute
  '/api/invite-codes/validate': typeof ApiInviteCodesValidateRoute
  '/api/payment/callback': typeof ApiPaymentCallbackRoute
  '/api/payment/checkout': typeof ApiPaymentCheckoutRoute
  '/api/storage/upload-image': typeof ApiStorageUploadImageRoute
  '/api/tickets/$id': typeof ApiTicketsIdRoute
  '/api/user/credits': typeof ApiUserCreditsRoute
  '/api/user/info': typeof ApiUserInfoRoute
  '/api/user/is-email-verified': typeof ApiUserIsEmailVerifiedRoute
  '/api/user/orders': typeof ApiUserOrdersRoute
  '/api/user/permissions': typeof ApiUserPermissionsRoute
  '/api/user/profile': typeof ApiUserProfileRoute
  '/api/wiki/ask': typeof ApiWikiAskRoute
  '/api/wiki/asset': typeof ApiWikiAssetRoute
  '/api/wiki/context': typeof ApiWikiContextRoute
  '/api/wiki/contexts': typeof ApiWikiContextsRoute
  '/api/admin/config/custom': typeof ApiAdminConfigCustomRoute
  '/api/admin/roles/assign': typeof ApiAdminRolesAssignRoute
  '/api/admin/roles/permissions': typeof ApiAdminRolesPermissionsRoute
  '/api/admin/settings/test': typeof ApiAdminSettingsTestRoute
  '/api/admin/tickets/$id': typeof ApiAdminTicketsIdRoute
  '/api/admin/users/credits': typeof ApiAdminUsersCreditsRoute
  '/api/ai-support/widget/$publicKey': typeof ApiAiSupportWidgetPublicKeyRouteWithChildren
  '/api/payment/notify/$provider': typeof ApiPaymentNotifyProviderRoute
  '/api/user/subscriptions/cancel': typeof ApiUserSubscriptionsCancelRoute
  '/api/user/subscriptions/current': typeof ApiUserSubscriptionsCurrentRoute
  '/api/admin/roles/': typeof ApiAdminRolesIndexRoute
  '/api/admin/users/': typeof ApiAdminUsersIndexRoute
  '/api/user/subscriptions/': typeof ApiUserSubscriptionsIndexRoute
  '/api/ai-support/widget/$publicKey/escalations': typeof ApiAiSupportWidgetPublicKeyEscalationsRoute
  '/api/ai-support/widget/$publicKey/leads': typeof ApiAiSupportWidgetPublicKeyLeadsRoute
  '/api/ai-support/widget/$publicKey/messages': typeof ApiAiSupportWidgetPublicKeyMessagesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/settings'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/categories'
    | '/admin/credits'
    | '/admin/invite-codes'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/api/apikeys'
    | '/api/credits'
    | '/api/tickets'
    | '/blog/$slug'
    | '/settings/ai-support'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/chat'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/tickets'
    | '/settings/wiki-assistant'
    | '/admin/'
    | '/blog/'
    | '/settings/'
    | '/api/admin/categories'
    | '/api/admin/config'
    | '/api/admin/credits'
    | '/api/admin/invite-codes'
    | '/api/admin/orders'
    | '/api/admin/permissions'
    | '/api/admin/posts'
    | '/api/admin/subscriptions'
    | '/api/admin/tickets'
    | '/api/ai-support/agent-runs'
    | '/api/ai-support/agent-tokens'
    | '/api/ai-support/audit-logs'
    | '/api/ai-support/chatbots'
    | '/api/ai-support/config-versions'
    | '/api/ai-support/conversation-messages'
    | '/api/ai-support/conversations'
    | '/api/ai-support/escalations'
    | '/api/ai-support/human-support-settings'
    | '/api/ai-support/install-check'
    | '/api/ai-support/knowledge-sources'
    | '/api/ai-support/launch-operations'
    | '/api/ai-support/leads'
    | '/api/ai-support/overview'
    | '/api/ai-support/prompt-persona'
    | '/api/ai-support/sync-jobs'
    | '/api/ai-support/usage'
    | '/api/ai-support/widget-appearance'
    | '/api/auth/$'
    | '/api/auth/token'
    | '/api/config/public'
    | '/api/docqa/ingest'
    | '/api/internal/credits'
    | '/api/internal/session'
    | '/api/invite-codes/redeem'
    | '/api/invite-codes/validate'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/storage/upload-image'
    | '/api/tickets/$id'
    | '/api/user/credits'
    | '/api/user/info'
    | '/api/user/is-email-verified'
    | '/api/user/orders'
    | '/api/user/permissions'
    | '/api/user/profile'
    | '/api/wiki/ask'
    | '/api/wiki/asset'
    | '/api/wiki/context'
    | '/api/wiki/contexts'
    | '/api/admin/config/custom'
    | '/api/admin/roles/assign'
    | '/api/admin/roles/permissions'
    | '/api/admin/settings/test'
    | '/api/admin/tickets/$id'
    | '/api/admin/users/credits'
    | '/api/ai-support/widget/$publicKey'
    | '/api/payment/notify/$provider'
    | '/api/user/subscriptions/cancel'
    | '/api/user/subscriptions/current'
    | '/api/admin/roles/'
    | '/api/admin/users/'
    | '/api/user/subscriptions/'
    | '/api/ai-support/widget/$publicKey/escalations'
    | '/api/ai-support/widget/$publicKey/leads'
    | '/api/ai-support/widget/$publicKey/messages'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/admin/categories'
    | '/admin/credits'
    | '/admin/invite-codes'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/api/apikeys'
    | '/api/credits'
    | '/api/tickets'
    | '/blog/$slug'
    | '/settings/ai-support'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/chat'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/tickets'
    | '/settings/wiki-assistant'
    | '/admin'
    | '/blog'
    | '/settings'
    | '/api/admin/categories'
    | '/api/admin/config'
    | '/api/admin/credits'
    | '/api/admin/invite-codes'
    | '/api/admin/orders'
    | '/api/admin/permissions'
    | '/api/admin/posts'
    | '/api/admin/subscriptions'
    | '/api/admin/tickets'
    | '/api/ai-support/agent-runs'
    | '/api/ai-support/agent-tokens'
    | '/api/ai-support/audit-logs'
    | '/api/ai-support/chatbots'
    | '/api/ai-support/config-versions'
    | '/api/ai-support/conversation-messages'
    | '/api/ai-support/conversations'
    | '/api/ai-support/escalations'
    | '/api/ai-support/human-support-settings'
    | '/api/ai-support/install-check'
    | '/api/ai-support/knowledge-sources'
    | '/api/ai-support/launch-operations'
    | '/api/ai-support/leads'
    | '/api/ai-support/overview'
    | '/api/ai-support/prompt-persona'
    | '/api/ai-support/sync-jobs'
    | '/api/ai-support/usage'
    | '/api/ai-support/widget-appearance'
    | '/api/auth/$'
    | '/api/auth/token'
    | '/api/config/public'
    | '/api/docqa/ingest'
    | '/api/internal/credits'
    | '/api/internal/session'
    | '/api/invite-codes/redeem'
    | '/api/invite-codes/validate'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/storage/upload-image'
    | '/api/tickets/$id'
    | '/api/user/credits'
    | '/api/user/info'
    | '/api/user/is-email-verified'
    | '/api/user/orders'
    | '/api/user/permissions'
    | '/api/user/profile'
    | '/api/wiki/ask'
    | '/api/wiki/asset'
    | '/api/wiki/context'
    | '/api/wiki/contexts'
    | '/api/admin/config/custom'
    | '/api/admin/roles/assign'
    | '/api/admin/roles/permissions'
    | '/api/admin/settings/test'
    | '/api/admin/tickets/$id'
    | '/api/admin/users/credits'
    | '/api/ai-support/widget/$publicKey'
    | '/api/payment/notify/$provider'
    | '/api/user/subscriptions/cancel'
    | '/api/user/subscriptions/current'
    | '/api/admin/roles'
    | '/api/admin/users'
    | '/api/user/subscriptions'
    | '/api/ai-support/widget/$publicKey/escalations'
    | '/api/ai-support/widget/$publicKey/leads'
    | '/api/ai-support/widget/$publicKey/messages'
  id:
    | '__root__'
    | '/'
    | '/(pages)'
    | '/admin'
    | '/settings'
    | '/pricing'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(auth)/verify-email'
    | '/(pages)/privacy-policy'
    | '/(pages)/terms-of-service'
    | '/admin/categories'
    | '/admin/credits'
    | '/admin/invite-codes'
    | '/admin/payments'
    | '/admin/permissions'
    | '/admin/posts'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/tickets'
    | '/admin/users'
    | '/api/apikeys'
    | '/api/credits'
    | '/api/tickets'
    | '/blog/$slug'
    | '/settings/ai-support'
    | '/settings/apikeys'
    | '/settings/billing'
    | '/settings/chat'
    | '/settings/credits'
    | '/settings/payments'
    | '/settings/profile'
    | '/settings/tickets'
    | '/settings/wiki-assistant'
    | '/admin/'
    | '/blog/'
    | '/settings/'
    | '/api/admin/categories'
    | '/api/admin/config'
    | '/api/admin/credits'
    | '/api/admin/invite-codes'
    | '/api/admin/orders'
    | '/api/admin/permissions'
    | '/api/admin/posts'
    | '/api/admin/subscriptions'
    | '/api/admin/tickets'
    | '/api/ai-support/agent-runs'
    | '/api/ai-support/agent-tokens'
    | '/api/ai-support/audit-logs'
    | '/api/ai-support/chatbots'
    | '/api/ai-support/config-versions'
    | '/api/ai-support/conversation-messages'
    | '/api/ai-support/conversations'
    | '/api/ai-support/escalations'
    | '/api/ai-support/human-support-settings'
    | '/api/ai-support/install-check'
    | '/api/ai-support/knowledge-sources'
    | '/api/ai-support/launch-operations'
    | '/api/ai-support/leads'
    | '/api/ai-support/overview'
    | '/api/ai-support/prompt-persona'
    | '/api/ai-support/sync-jobs'
    | '/api/ai-support/usage'
    | '/api/ai-support/widget-appearance'
    | '/api/auth/$'
    | '/api/auth/token'
    | '/api/config/public'
    | '/api/docqa/ingest'
    | '/api/internal/credits'
    | '/api/internal/session'
    | '/api/invite-codes/redeem'
    | '/api/invite-codes/validate'
    | '/api/payment/callback'
    | '/api/payment/checkout'
    | '/api/storage/upload-image'
    | '/api/tickets/$id'
    | '/api/user/credits'
    | '/api/user/info'
    | '/api/user/is-email-verified'
    | '/api/user/orders'
    | '/api/user/permissions'
    | '/api/user/profile'
    | '/api/wiki/ask'
    | '/api/wiki/asset'
    | '/api/wiki/context'
    | '/api/wiki/contexts'
    | '/api/admin/config/custom'
    | '/api/admin/roles/assign'
    | '/api/admin/roles/permissions'
    | '/api/admin/settings/test'
    | '/api/admin/tickets/$id'
    | '/api/admin/users/credits'
    | '/api/ai-support/widget/$publicKey'
    | '/api/payment/notify/$provider'
    | '/api/user/subscriptions/cancel'
    | '/api/user/subscriptions/current'
    | '/api/admin/roles/'
    | '/api/admin/users/'
    | '/api/user/subscriptions/'
    | '/api/ai-support/widget/$publicKey/escalations'
    | '/api/ai-support/widget/$publicKey/leads'
    | '/api/ai-support/widget/$publicKey/messages'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  pagesRouteRoute: typeof pagesRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authVerifyEmailRoute: typeof authVerifyEmailRoute
  ApiApikeysRoute: typeof ApiApikeysRoute
  ApiCreditsRoute: typeof ApiCreditsRoute
  ApiTicketsRoute: typeof ApiTicketsRouteWithChildren
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAdminCategoriesRoute: typeof ApiAdminCategoriesRoute
  ApiAdminConfigRoute: typeof ApiAdminConfigRouteWithChildren
  ApiAdminCreditsRoute: typeof ApiAdminCreditsRoute
  ApiAdminInviteCodesRoute: typeof ApiAdminInviteCodesRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRoute
  ApiAdminPermissionsRoute: typeof ApiAdminPermissionsRoute
  ApiAdminPostsRoute: typeof ApiAdminPostsRoute
  ApiAdminSubscriptionsRoute: typeof ApiAdminSubscriptionsRoute
  ApiAdminTicketsRoute: typeof ApiAdminTicketsRouteWithChildren
  ApiAiSupportAgentRunsRoute: typeof ApiAiSupportAgentRunsRoute
  ApiAiSupportAgentTokensRoute: typeof ApiAiSupportAgentTokensRoute
  ApiAiSupportAuditLogsRoute: typeof ApiAiSupportAuditLogsRoute
  ApiAiSupportChatbotsRoute: typeof ApiAiSupportChatbotsRoute
  ApiAiSupportConfigVersionsRoute: typeof ApiAiSupportConfigVersionsRoute
  ApiAiSupportConversationMessagesRoute: typeof ApiAiSupportConversationMessagesRoute
  ApiAiSupportConversationsRoute: typeof ApiAiSupportConversationsRoute
  ApiAiSupportEscalationsRoute: typeof ApiAiSupportEscalationsRoute
  ApiAiSupportHumanSupportSettingsRoute: typeof ApiAiSupportHumanSupportSettingsRoute
  ApiAiSupportInstallCheckRoute: typeof ApiAiSupportInstallCheckRoute
  ApiAiSupportKnowledgeSourcesRoute: typeof ApiAiSupportKnowledgeSourcesRoute
  ApiAiSupportLaunchOperationsRoute: typeof ApiAiSupportLaunchOperationsRoute
  ApiAiSupportLeadsRoute: typeof ApiAiSupportLeadsRoute
  ApiAiSupportOverviewRoute: typeof ApiAiSupportOverviewRoute
  ApiAiSupportPromptPersonaRoute: typeof ApiAiSupportPromptPersonaRoute
  ApiAiSupportSyncJobsRoute: typeof ApiAiSupportSyncJobsRoute
  ApiAiSupportUsageRoute: typeof ApiAiSupportUsageRoute
  ApiAiSupportWidgetAppearanceRoute: typeof ApiAiSupportWidgetAppearanceRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthTokenRoute: typeof ApiAuthTokenRoute
  ApiConfigPublicRoute: typeof ApiConfigPublicRoute
  ApiDocqaIngestRoute: typeof ApiDocqaIngestRoute
  ApiInternalCreditsRoute: typeof ApiInternalCreditsRoute
  ApiInternalSessionRoute: typeof ApiInternalSessionRoute
  ApiInviteCodesRedeemRoute: typeof ApiInviteCodesRedeemRoute
  ApiInviteCodesValidateRoute: typeof ApiInviteCodesValidateRoute
  ApiPaymentCallbackRoute: typeof ApiPaymentCallbackRoute
  ApiPaymentCheckoutRoute: typeof ApiPaymentCheckoutRoute
  ApiStorageUploadImageRoute: typeof ApiStorageUploadImageRoute
  ApiUserCreditsRoute: typeof ApiUserCreditsRoute
  ApiUserInfoRoute: typeof ApiUserInfoRoute
  ApiUserIsEmailVerifiedRoute: typeof ApiUserIsEmailVerifiedRoute
  ApiUserOrdersRoute: typeof ApiUserOrdersRoute
  ApiUserPermissionsRoute: typeof ApiUserPermissionsRoute
  ApiUserProfileRoute: typeof ApiUserProfileRoute
  ApiWikiAskRoute: typeof ApiWikiAskRoute
  ApiWikiAssetRoute: typeof ApiWikiAssetRoute
  ApiWikiContextRoute: typeof ApiWikiContextRoute
  ApiWikiContextsRoute: typeof ApiWikiContextsRoute
  ApiAdminRolesAssignRoute: typeof ApiAdminRolesAssignRoute
  ApiAdminRolesPermissionsRoute: typeof ApiAdminRolesPermissionsRoute
  ApiAdminSettingsTestRoute: typeof ApiAdminSettingsTestRoute
  ApiAdminUsersCreditsRoute: typeof ApiAdminUsersCreditsRoute
  ApiAiSupportWidgetPublicKeyRoute: typeof ApiAiSupportWidgetPublicKeyRouteWithChildren
  ApiPaymentNotifyProviderRoute: typeof ApiPaymentNotifyProviderRoute
  ApiUserSubscriptionsCancelRoute: typeof ApiUserSubscriptionsCancelRoute
  ApiUserSubscriptionsCurrentRoute: typeof ApiUserSubscriptionsCurrentRoute
  ApiAdminRolesIndexRoute: typeof ApiAdminRolesIndexRoute
  ApiAdminUsersIndexRoute: typeof ApiAdminUsersIndexRoute
  ApiUserSubscriptionsIndexRoute: typeof ApiUserSubscriptionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(pages)': {
      id: '/(pages)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof pagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/settings/wiki-assistant': {
      id: '/settings/wiki-assistant'
      path: '/wiki-assistant'
      fullPath: '/settings/wiki-assistant'
      preLoaderRoute: typeof SettingsWikiAssistantRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/tickets': {
      id: '/settings/tickets'
      path: '/tickets'
      fullPath: '/settings/tickets'
      preLoaderRoute: typeof SettingsTicketsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/payments': {
      id: '/settings/payments'
      path: '/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof SettingsPaymentsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/credits': {
      id: '/settings/credits'
      path: '/credits'
      fullPath: '/settings/credits'
      preLoaderRoute: typeof SettingsCreditsRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/chat': {
      id: '/settings/chat'
      path: '/chat'
      fullPath: '/settings/chat'
      preLoaderRoute: typeof SettingsChatRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/billing': {
      id: '/settings/billing'
      path: '/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof SettingsBillingRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/apikeys': {
      id: '/settings/apikeys'
      path: '/apikeys'
      fullPath: '/settings/apikeys'
      preLoaderRoute: typeof SettingsApikeysRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/ai-support': {
      id: '/settings/ai-support'
      path: '/ai-support'
      fullPath: '/settings/ai-support'
      preLoaderRoute: typeof SettingsAiSupportRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets': {
      id: '/api/tickets'
      path: '/api/tickets'
      fullPath: '/api/tickets'
      preLoaderRoute: typeof ApiTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/credits': {
      id: '/api/credits'
      path: '/api/credits'
      fullPath: '/api/credits'
      preLoaderRoute: typeof ApiCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/apikeys': {
      id: '/api/apikeys'
      path: '/api/apikeys'
      fullPath: '/api/apikeys'
      preLoaderRoute: typeof ApiApikeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tickets': {
      id: '/admin/tickets'
      path: '/tickets'
      fullPath: '/admin/tickets'
      preLoaderRoute: typeof AdminTicketsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/posts': {
      id: '/admin/posts'
      path: '/posts'
      fullPath: '/admin/posts'
      preLoaderRoute: typeof AdminPostsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/invite-codes': {
      id: '/admin/invite-codes'
      path: '/invite-codes'
      fullPath: '/admin/invite-codes'
      preLoaderRoute: typeof AdminInviteCodesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/credits': {
      id: '/admin/credits'
      path: '/credits'
      fullPath: '/admin/credits'
      preLoaderRoute: typeof AdminCreditsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(pages)/terms-of-service': {
      id: '/(pages)/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof pagesTermsOfServiceRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(pages)/privacy-policy': {
      id: '/(pages)/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof pagesPrivacyPolicyRouteImport
      parentRoute: typeof pagesRouteRoute
    }
    '/(auth)/verify-email': {
      id: '/(auth)/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof authVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki/contexts': {
      id: '/api/wiki/contexts'
      path: '/api/wiki/contexts'
      fullPath: '/api/wiki/contexts'
      preLoaderRoute: typeof ApiWikiContextsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki/context': {
      id: '/api/wiki/context'
      path: '/api/wiki/context'
      fullPath: '/api/wiki/context'
      preLoaderRoute: typeof ApiWikiContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki/asset': {
      id: '/api/wiki/asset'
      path: '/api/wiki/asset'
      fullPath: '/api/wiki/asset'
      preLoaderRoute: typeof ApiWikiAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/wiki/ask': {
      id: '/api/wiki/ask'
      path: '/api/wiki/ask'
      fullPath: '/api/wiki/ask'
      preLoaderRoute: typeof ApiWikiAskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/profile': {
      id: '/api/user/profile'
      path: '/api/user/profile'
      fullPath: '/api/user/profile'
      preLoaderRoute: typeof ApiUserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/permissions': {
      id: '/api/user/permissions'
      path: '/api/user/permissions'
      fullPath: '/api/user/permissions'
      preLoaderRoute: typeof ApiUserPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/orders': {
      id: '/api/user/orders'
      path: '/api/user/orders'
      fullPath: '/api/user/orders'
      preLoaderRoute: typeof ApiUserOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/is-email-verified': {
      id: '/api/user/is-email-verified'
      path: '/api/user/is-email-verified'
      fullPath: '/api/user/is-email-verified'
      preLoaderRoute: typeof ApiUserIsEmailVerifiedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/info': {
      id: '/api/user/info'
      path: '/api/user/info'
      fullPath: '/api/user/info'
      preLoaderRoute: typeof ApiUserInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/credits': {
      id: '/api/user/credits'
      path: '/api/user/credits'
      fullPath: '/api/user/credits'
      preLoaderRoute: typeof ApiUserCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/$id': {
      id: '/api/tickets/$id'
      path: '/$id'
      fullPath: '/api/tickets/$id'
      preLoaderRoute: typeof ApiTicketsIdRouteImport
      parentRoute: typeof ApiTicketsRoute
    }
    '/api/storage/upload-image': {
      id: '/api/storage/upload-image'
      path: '/api/storage/upload-image'
      fullPath: '/api/storage/upload-image'
      preLoaderRoute: typeof ApiStorageUploadImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/checkout': {
      id: '/api/payment/checkout'
      path: '/api/payment/checkout'
      fullPath: '/api/payment/checkout'
      preLoaderRoute: typeof ApiPaymentCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/callback': {
      id: '/api/payment/callback'
      path: '/api/payment/callback'
      fullPath: '/api/payment/callback'
      preLoaderRoute: typeof ApiPaymentCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invite-codes/validate': {
      id: '/api/invite-codes/validate'
      path: '/api/invite-codes/validate'
      fullPath: '/api/invite-codes/validate'
      preLoaderRoute: typeof ApiInviteCodesValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/invite-codes/redeem': {
      id: '/api/invite-codes/redeem'
      path: '/api/invite-codes/redeem'
      fullPath: '/api/invite-codes/redeem'
      preLoaderRoute: typeof ApiInviteCodesRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/session': {
      id: '/api/internal/session'
      path: '/api/internal/session'
      fullPath: '/api/internal/session'
      preLoaderRoute: typeof ApiInternalSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/credits': {
      id: '/api/internal/credits'
      path: '/api/internal/credits'
      fullPath: '/api/internal/credits'
      preLoaderRoute: typeof ApiInternalCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/docqa/ingest': {
      id: '/api/docqa/ingest'
      path: '/api/docqa/ingest'
      fullPath: '/api/docqa/ingest'
      preLoaderRoute: typeof ApiDocqaIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config/public': {
      id: '/api/config/public'
      path: '/api/config/public'
      fullPath: '/api/config/public'
      preLoaderRoute: typeof ApiConfigPublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/token': {
      id: '/api/auth/token'
      path: '/api/auth/token'
      fullPath: '/api/auth/token'
      preLoaderRoute: typeof ApiAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/widget-appearance': {
      id: '/api/ai-support/widget-appearance'
      path: '/api/ai-support/widget-appearance'
      fullPath: '/api/ai-support/widget-appearance'
      preLoaderRoute: typeof ApiAiSupportWidgetAppearanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/usage': {
      id: '/api/ai-support/usage'
      path: '/api/ai-support/usage'
      fullPath: '/api/ai-support/usage'
      preLoaderRoute: typeof ApiAiSupportUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/sync-jobs': {
      id: '/api/ai-support/sync-jobs'
      path: '/api/ai-support/sync-jobs'
      fullPath: '/api/ai-support/sync-jobs'
      preLoaderRoute: typeof ApiAiSupportSyncJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/prompt-persona': {
      id: '/api/ai-support/prompt-persona'
      path: '/api/ai-support/prompt-persona'
      fullPath: '/api/ai-support/prompt-persona'
      preLoaderRoute: typeof ApiAiSupportPromptPersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/overview': {
      id: '/api/ai-support/overview'
      path: '/api/ai-support/overview'
      fullPath: '/api/ai-support/overview'
      preLoaderRoute: typeof ApiAiSupportOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/leads': {
      id: '/api/ai-support/leads'
      path: '/api/ai-support/leads'
      fullPath: '/api/ai-support/leads'
      preLoaderRoute: typeof ApiAiSupportLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/launch-operations': {
      id: '/api/ai-support/launch-operations'
      path: '/api/ai-support/launch-operations'
      fullPath: '/api/ai-support/launch-operations'
      preLoaderRoute: typeof ApiAiSupportLaunchOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/knowledge-sources': {
      id: '/api/ai-support/knowledge-sources'
      path: '/api/ai-support/knowledge-sources'
      fullPath: '/api/ai-support/knowledge-sources'
      preLoaderRoute: typeof ApiAiSupportKnowledgeSourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/install-check': {
      id: '/api/ai-support/install-check'
      path: '/api/ai-support/install-check'
      fullPath: '/api/ai-support/install-check'
      preLoaderRoute: typeof ApiAiSupportInstallCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/human-support-settings': {
      id: '/api/ai-support/human-support-settings'
      path: '/api/ai-support/human-support-settings'
      fullPath: '/api/ai-support/human-support-settings'
      preLoaderRoute: typeof ApiAiSupportHumanSupportSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/escalations': {
      id: '/api/ai-support/escalations'
      path: '/api/ai-support/escalations'
      fullPath: '/api/ai-support/escalations'
      preLoaderRoute: typeof ApiAiSupportEscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/conversations': {
      id: '/api/ai-support/conversations'
      path: '/api/ai-support/conversations'
      fullPath: '/api/ai-support/conversations'
      preLoaderRoute: typeof ApiAiSupportConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/conversation-messages': {
      id: '/api/ai-support/conversation-messages'
      path: '/api/ai-support/conversation-messages'
      fullPath: '/api/ai-support/conversation-messages'
      preLoaderRoute: typeof ApiAiSupportConversationMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/config-versions': {
      id: '/api/ai-support/config-versions'
      path: '/api/ai-support/config-versions'
      fullPath: '/api/ai-support/config-versions'
      preLoaderRoute: typeof ApiAiSupportConfigVersionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/chatbots': {
      id: '/api/ai-support/chatbots'
      path: '/api/ai-support/chatbots'
      fullPath: '/api/ai-support/chatbots'
      preLoaderRoute: typeof ApiAiSupportChatbotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/audit-logs': {
      id: '/api/ai-support/audit-logs'
      path: '/api/ai-support/audit-logs'
      fullPath: '/api/ai-support/audit-logs'
      preLoaderRoute: typeof ApiAiSupportAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/agent-tokens': {
      id: '/api/ai-support/agent-tokens'
      path: '/api/ai-support/agent-tokens'
      fullPath: '/api/ai-support/agent-tokens'
      preLoaderRoute: typeof ApiAiSupportAgentTokensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/agent-runs': {
      id: '/api/ai-support/agent-runs'
      path: '/api/ai-support/agent-runs'
      fullPath: '/api/ai-support/agent-runs'
      preLoaderRoute: typeof ApiAiSupportAgentRunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tickets': {
      id: '/api/admin/tickets'
      path: '/api/admin/tickets'
      fullPath: '/api/admin/tickets'
      preLoaderRoute: typeof ApiAdminTicketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/subscriptions': {
      id: '/api/admin/subscriptions'
      path: '/api/admin/subscriptions'
      fullPath: '/api/admin/subscriptions'
      preLoaderRoute: typeof ApiAdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/posts': {
      id: '/api/admin/posts'
      path: '/api/admin/posts'
      fullPath: '/api/admin/posts'
      preLoaderRoute: typeof ApiAdminPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/permissions': {
      id: '/api/admin/permissions'
      path: '/api/admin/permissions'
      fullPath: '/api/admin/permissions'
      preLoaderRoute: typeof ApiAdminPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invite-codes': {
      id: '/api/admin/invite-codes'
      path: '/api/admin/invite-codes'
      fullPath: '/api/admin/invite-codes'
      preLoaderRoute: typeof ApiAdminInviteCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/credits': {
      id: '/api/admin/credits'
      path: '/api/admin/credits'
      fullPath: '/api/admin/credits'
      preLoaderRoute: typeof ApiAdminCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config': {
      id: '/api/admin/config'
      path: '/api/admin/config'
      fullPath: '/api/admin/config'
      preLoaderRoute: typeof ApiAdminConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/categories': {
      id: '/api/admin/categories'
      path: '/api/admin/categories'
      fullPath: '/api/admin/categories'
      preLoaderRoute: typeof ApiAdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/subscriptions/': {
      id: '/api/user/subscriptions/'
      path: '/api/user/subscriptions'
      fullPath: '/api/user/subscriptions/'
      preLoaderRoute: typeof ApiUserSubscriptionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/': {
      id: '/api/admin/users/'
      path: '/api/admin/users'
      fullPath: '/api/admin/users/'
      preLoaderRoute: typeof ApiAdminUsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/roles/': {
      id: '/api/admin/roles/'
      path: '/api/admin/roles'
      fullPath: '/api/admin/roles/'
      preLoaderRoute: typeof ApiAdminRolesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/subscriptions/current': {
      id: '/api/user/subscriptions/current'
      path: '/api/user/subscriptions/current'
      fullPath: '/api/user/subscriptions/current'
      preLoaderRoute: typeof ApiUserSubscriptionsCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/user/subscriptions/cancel': {
      id: '/api/user/subscriptions/cancel'
      path: '/api/user/subscriptions/cancel'
      fullPath: '/api/user/subscriptions/cancel'
      preLoaderRoute: typeof ApiUserSubscriptionsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/notify/$provider': {
      id: '/api/payment/notify/$provider'
      path: '/api/payment/notify/$provider'
      fullPath: '/api/payment/notify/$provider'
      preLoaderRoute: typeof ApiPaymentNotifyProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-support/widget/$publicKey': {
      id: '/api/ai-support/widget/$publicKey'
      path: '/api/ai-support/widget/$publicKey'
      fullPath: '/api/ai-support/widget/$publicKey'
      preLoaderRoute: typeof ApiAiSupportWidgetPublicKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users/credits': {
      id: '/api/admin/users/credits'
      path: '/api/admin/users/credits'
      fullPath: '/api/admin/users/credits'
      preLoaderRoute: typeof ApiAdminUsersCreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/tickets/$id': {
      id: '/api/admin/tickets/$id'
      path: '/$id'
      fullPath: '/api/admin/tickets/$id'
      preLoaderRoute: typeof ApiAdminTicketsIdRouteImport
      parentRoute: typeof ApiAdminTicketsRoute
    }
    '/api/admin/settings/test': {
      id: '/api/admin/settings/test'
      path: '/api/admin/settings/test'
      fullPath: '/api/admin/settings/test'
      preLoaderRoute: typeof ApiAdminSettingsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/roles/permissions': {
      id: '/api/admin/roles/permissions'
      path: '/api/admin/roles/permissions'
      fullPath: '/api/admin/roles/permissions'
      preLoaderRoute: typeof ApiAdminRolesPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/roles/assign': {
      id: '/api/admin/roles/assign'
      path: '/api/admin/roles/assign'
      fullPath: '/api/admin/roles/assign'
      preLoaderRoute: typeof ApiAdminRolesAssignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/config/custom': {
      id: '/api/admin/config/custom'
      path: '/custom'
      fullPath: '/api/admin/config/custom'
      preLoaderRoute: typeof ApiAdminConfigCustomRouteImport
      parentRoute: typeof ApiAdminConfigRoute
    }
    '/api/ai-support/widget/$publicKey/messages': {
      id: '/api/ai-support/widget/$publicKey/messages'
      path: '/messages'
      fullPath: '/api/ai-support/widget/$publicKey/messages'
      preLoaderRoute: typeof ApiAiSupportWidgetPublicKeyMessagesRouteImport
      parentRoute: typeof ApiAiSupportWidgetPublicKeyRoute
    }
    '/api/ai-support/widget/$publicKey/leads': {
      id: '/api/ai-support/widget/$publicKey/leads'
      path: '/leads'
      fullPath: '/api/ai-support/widget/$publicKey/leads'
      preLoaderRoute: typeof ApiAiSupportWidgetPublicKeyLeadsRouteImport
      parentRoute: typeof ApiAiSupportWidgetPublicKeyRoute
    }
    '/api/ai-support/widget/$publicKey/escalations': {
      id: '/api/ai-support/widget/$publicKey/escalations'
      path: '/escalations'
      fullPath: '/api/ai-support/widget/$publicKey/escalations'
      preLoaderRoute: typeof ApiAiSupportWidgetPublicKeyEscalationsRouteImport
      parentRoute: typeof ApiAiSupportWidgetPublicKeyRoute
    }
  }
}

interface pagesRouteRouteChildren {
  pagesPrivacyPolicyRoute: typeof pagesPrivacyPolicyRoute
  pagesTermsOfServiceRoute: typeof pagesTermsOfServiceRoute
}

const pagesRouteRouteChildren: pagesRouteRouteChildren = {
  pagesPrivacyPolicyRoute: pagesPrivacyPolicyRoute,
  pagesTermsOfServiceRoute: pagesTermsOfServiceRoute,
}

const pagesRouteRouteWithChildren = pagesRouteRoute._addFileChildren(
  pagesRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCreditsRoute: typeof AdminCreditsRoute
  AdminInviteCodesRoute: typeof AdminInviteCodesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminPostsRoute: typeof AdminPostsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
  AdminTicketsRoute: typeof AdminTicketsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCreditsRoute: AdminCreditsRoute,
  AdminInviteCodesRoute: AdminInviteCodesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminPostsRoute: AdminPostsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
  AdminTicketsRoute: AdminTicketsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAiSupportRoute: typeof SettingsAiSupportRoute
  SettingsApikeysRoute: typeof SettingsApikeysRoute
  SettingsBillingRoute: typeof SettingsBillingRoute
  SettingsChatRoute: typeof SettingsChatRoute
  SettingsCreditsRoute: typeof SettingsCreditsRoute
  SettingsPaymentsRoute: typeof SettingsPaymentsRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsTicketsRoute: typeof SettingsTicketsRoute
  SettingsWikiAssistantRoute: typeof SettingsWikiAssistantRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAiSupportRoute: SettingsAiSupportRoute,
  SettingsApikeysRoute: SettingsApikeysRoute,
  SettingsBillingRoute: SettingsBillingRoute,
  SettingsChatRoute: SettingsChatRoute,
  SettingsCreditsRoute: SettingsCreditsRoute,
  SettingsPaymentsRoute: SettingsPaymentsRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsTicketsRoute: SettingsTicketsRoute,
  SettingsWikiAssistantRoute: SettingsWikiAssistantRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface ApiTicketsRouteChildren {
  ApiTicketsIdRoute: typeof ApiTicketsIdRoute
}

const ApiTicketsRouteChildren: ApiTicketsRouteChildren = {
  ApiTicketsIdRoute: ApiTicketsIdRoute,
}

const ApiTicketsRouteWithChildren = ApiTicketsRoute._addFileChildren(
  ApiTicketsRouteChildren,
)

interface ApiAdminConfigRouteChildren {
  ApiAdminConfigCustomRoute: typeof ApiAdminConfigCustomRoute
}

const ApiAdminConfigRouteChildren: ApiAdminConfigRouteChildren = {
  ApiAdminConfigCustomRoute: ApiAdminConfigCustomRoute,
}

const ApiAdminConfigRouteWithChildren = ApiAdminConfigRoute._addFileChildren(
  ApiAdminConfigRouteChildren,
)

interface ApiAdminTicketsRouteChildren {
  ApiAdminTicketsIdRoute: typeof ApiAdminTicketsIdRoute
}

const ApiAdminTicketsRouteChildren: ApiAdminTicketsRouteChildren = {
  ApiAdminTicketsIdRoute: ApiAdminTicketsIdRoute,
}

const ApiAdminTicketsRouteWithChildren = ApiAdminTicketsRoute._addFileChildren(
  ApiAdminTicketsRouteChildren,
)

interface ApiAiSupportWidgetPublicKeyRouteChildren {
  ApiAiSupportWidgetPublicKeyEscalationsRoute: typeof ApiAiSupportWidgetPublicKeyEscalationsRoute
  ApiAiSupportWidgetPublicKeyLeadsRoute: typeof ApiAiSupportWidgetPublicKeyLeadsRoute
  ApiAiSupportWidgetPublicKeyMessagesRoute: typeof ApiAiSupportWidgetPublicKeyMessagesRoute
}

const ApiAiSupportWidgetPublicKeyRouteChildren: ApiAiSupportWidgetPublicKeyRouteChildren =
  {
    ApiAiSupportWidgetPublicKeyEscalationsRoute:
      ApiAiSupportWidgetPublicKeyEscalationsRoute,
    ApiAiSupportWidgetPublicKeyLeadsRoute:
      ApiAiSupportWidgetPublicKeyLeadsRoute,
    ApiAiSupportWidgetPublicKeyMessagesRoute:
      ApiAiSupportWidgetPublicKeyMessagesRoute,
  }

const ApiAiSupportWidgetPublicKeyRouteWithChildren =
  ApiAiSupportWidgetPublicKeyRoute._addFileChildren(
    ApiAiSupportWidgetPublicKeyRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  pagesRouteRoute: pagesRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authVerifyEmailRoute: authVerifyEmailRoute,
  ApiApikeysRoute: ApiApikeysRoute,
  ApiCreditsRoute: ApiCreditsRoute,
  ApiTicketsRoute: ApiTicketsRouteWithChildren,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAdminCategoriesRoute: ApiAdminCategoriesRoute,
  ApiAdminConfigRoute: ApiAdminConfigRouteWithChildren,
  ApiAdminCreditsRoute: ApiAdminCreditsRoute,
  ApiAdminInviteCodesRoute: ApiAdminInviteCodesRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRoute,
  ApiAdminPermissionsRoute: ApiAdminPermissionsRoute,
  ApiAdminPostsRoute: ApiAdminPostsRoute,
  ApiAdminSubscriptionsRoute: ApiAdminSubscriptionsRoute,
  ApiAdminTicketsRoute: ApiAdminTicketsRouteWithChildren,
  ApiAiSupportAgentRunsRoute: ApiAiSupportAgentRunsRoute,
  ApiAiSupportAgentTokensRoute: ApiAiSupportAgentTokensRoute,
  ApiAiSupportAuditLogsRoute: ApiAiSupportAuditLogsRoute,
  ApiAiSupportChatbotsRoute: ApiAiSupportChatbotsRoute,
  ApiAiSupportConfigVersionsRoute: ApiAiSupportConfigVersionsRoute,
  ApiAiSupportConversationMessagesRoute: ApiAiSupportConversationMessagesRoute,
  ApiAiSupportConversationsRoute: ApiAiSupportConversationsRoute,
  ApiAiSupportEscalationsRoute: ApiAiSupportEscalationsRoute,
  ApiAiSupportHumanSupportSettingsRoute: ApiAiSupportHumanSupportSettingsRoute,
  ApiAiSupportInstallCheckRoute: ApiAiSupportInstallCheckRoute,
  ApiAiSupportKnowledgeSourcesRoute: ApiAiSupportKnowledgeSourcesRoute,
  ApiAiSupportLaunchOperationsRoute: ApiAiSupportLaunchOperationsRoute,
  ApiAiSupportLeadsRoute: ApiAiSupportLeadsRoute,
  ApiAiSupportOverviewRoute: ApiAiSupportOverviewRoute,
  ApiAiSupportPromptPersonaRoute: ApiAiSupportPromptPersonaRoute,
  ApiAiSupportSyncJobsRoute: ApiAiSupportSyncJobsRoute,
  ApiAiSupportUsageRoute: ApiAiSupportUsageRoute,
  ApiAiSupportWidgetAppearanceRoute: ApiAiSupportWidgetAppearanceRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthTokenRoute: ApiAuthTokenRoute,
  ApiConfigPublicRoute: ApiConfigPublicRoute,
  ApiDocqaIngestRoute: ApiDocqaIngestRoute,
  ApiInternalCreditsRoute: ApiInternalCreditsRoute,
  ApiInternalSessionRoute: ApiInternalSessionRoute,
  ApiInviteCodesRedeemRoute: ApiInviteCodesRedeemRoute,
  ApiInviteCodesValidateRoute: ApiInviteCodesValidateRoute,
  ApiPaymentCallbackRoute: ApiPaymentCallbackRoute,
  ApiPaymentCheckoutRoute: ApiPaymentCheckoutRoute,
  ApiStorageUploadImageRoute: ApiStorageUploadImageRoute,
  ApiUserCreditsRoute: ApiUserCreditsRoute,
  ApiUserInfoRoute: ApiUserInfoRoute,
  ApiUserIsEmailVerifiedRoute: ApiUserIsEmailVerifiedRoute,
  ApiUserOrdersRoute: ApiUserOrdersRoute,
  ApiUserPermissionsRoute: ApiUserPermissionsRoute,
  ApiUserProfileRoute: ApiUserProfileRoute,
  ApiWikiAskRoute: ApiWikiAskRoute,
  ApiWikiAssetRoute: ApiWikiAssetRoute,
  ApiWikiContextRoute: ApiWikiContextRoute,
  ApiWikiContextsRoute: ApiWikiContextsRoute,
  ApiAdminRolesAssignRoute: ApiAdminRolesAssignRoute,
  ApiAdminRolesPermissionsRoute: ApiAdminRolesPermissionsRoute,
  ApiAdminSettingsTestRoute: ApiAdminSettingsTestRoute,
  ApiAdminUsersCreditsRoute: ApiAdminUsersCreditsRoute,
  ApiAiSupportWidgetPublicKeyRoute:
    ApiAiSupportWidgetPublicKeyRouteWithChildren,
  ApiPaymentNotifyProviderRoute: ApiPaymentNotifyProviderRoute,
  ApiUserSubscriptionsCancelRoute: ApiUserSubscriptionsCancelRoute,
  ApiUserSubscriptionsCurrentRoute: ApiUserSubscriptionsCurrentRoute,
  ApiAdminRolesIndexRoute: ApiAdminRolesIndexRoute,
  ApiAdminUsersIndexRoute: ApiAdminUsersIndexRoute,
  ApiUserSubscriptionsIndexRoute: ApiUserSubscriptionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
